name: Auto Version

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  auto-version:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'RELEASE')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Pref Editor bot"

      - name: Install dependencies
        run: npm ci

      - name: Determine version bump
        id: version-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          echo "PR has RELEASE label - determining version bump type"

          # Check for additional labels to determine version type
          LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          echo "PR Labels: $LABELS"

          if [[ "$LABELS" =~ major ]] || [[ "$PR_TITLE" =~ ^BREAKING: ]] || [[ "$PR_TITLE" =~ ^breaking: ]]; then
            echo "VERSION_TYPE=major" >> $GITHUB_OUTPUT
            echo "Detected: MAJOR version bump"
          elif [[ "$LABELS" =~ minor ]] || [[ "$PR_TITLE" =~ ^feat: ]] || [[ "$PR_TITLE" =~ ^FEAT: ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_OUTPUT
            echo "Detected: MINOR version bump"
          elif [[ "$LABELS" =~ patch ]] || [[ "$PR_TITLE" =~ ^fix: ]] || [[ "$PR_TITLE" =~ ^FIX: ]]; then
            echo "VERSION_TYPE=patch" >> $GITHUB_OUTPUT
            echo "Detected: PATCH version bump"
          else
            # Default to patch if no specific version type is detected
            echo "VERSION_TYPE=patch" >> $GITHUB_OUTPUT
            echo "Defaulting to PATCH version bump"
          fi

      - name: Run verification
        run: npm run verify

      - name: Bump version
        run: |
          npm version ${{ steps.version-type.outputs.VERSION_TYPE }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=v$NEW_VERSION" >> $GITHUB_ENV
          echo "Bumped to version: v$NEW_VERSION"

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "release: bump version to ${{ env.NEW_VERSION }}"
          git push origin main

      - name: Create and push tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
          echo "Created and pushed tag: ${{ env.NEW_VERSION }}"

      - name: Summary
        run: |
          echo "✅ Successfully created ${{ steps.version-type.outputs.VERSION_TYPE }} release: ${{ env.NEW_VERSION }}"
          echo "🚀 Release workflow will be triggered automatically"
